Display the reason of API calls errors
The PVE API enhance server side errors with a reason phrase, so that API clients
can get better informed what is wrong in the request.
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html

Without this patch:
node.lxc.create(vmid=202,
                   ostemplate='isoserv:vztmpl/debian-9.0-standard_20170530_amd64.tar.gz',
                   hostname='debian9',
                   storage='non_existent')

raise the exception
 File "build/bdist.linux-x86_64/egg/proxmoxer/core.py", line 79, in _request
proxmoxer.core.ResourceException: 500 Internal Server Error

with patch applied:
proxmoxer.core.ResourceException: 500 Internal Server Error storage 'non_existent' does not exists

This patch is needed for this ansible issue:
https://github.com/ansible/ansible/issues/25113